#!/usr/bin/env python3
"""Generate lib/vga2_8x16_cp866.py — the display font with Cyrillic glyphs.

Base: lib/vga2_8x16.py (CP437 VGA ROM font) — every existing glyph is kept
byte-identical so the UI looks unchanged. Only the CP866 Cyrillic slots are
replaced with glyphs from UNI-VGA (u_vga16.bdf, Dmitry Bolkhovityanov,
X license — a VGA-style 8x16 unicode font), plus two Bulgarian extras:

  0x80-0x9F  А-Я (U+0410..U+042F)
  0xA0-0xAF  а-п (U+0430..U+043F)
  0xE0-0xEF  р-я (U+0440..U+044F)
  0xF0/0xF1  Ё/ё      0xF2/0xF3  Є/є      0xF4/0xF5  Ї/ї
  0xF6/0xF7  Ў/ў      0xFC/0xFD  Ѝ/ѝ  (CP866 has №/¤ here — Bulgarian
                                        stressed И matters more)

The codepoint->byte transcoding table lives in ui.py (_CYR) and must match
this layout.

Usage:  python3 tools/gen_cp866_font.py path/to/u_vga16.bdf
"""

import sys
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# byte slot -> unicode codepoint (must mirror ui.py _CYR)
SLOTS = {0xF0: 0x401, 0xF1: 0x451, 0xF2: 0x404, 0xF3: 0x454,
         0xF4: 0x407, 0xF5: 0x457, 0xF6: 0x40E, 0xF7: 0x45E,
         0xFC: 0x40D, 0xFD: 0x45D}
for i in range(32):
    SLOTS[0x80 + i] = 0x410 + i        # А-Я
for i in range(16):
    SLOTS[0xA0 + i] = 0x430 + i        # а-п
    SLOTS[0xE0 + i] = 0x440 + i        # р-я


def parse_bdf(path, wanted):
    """-> {codepoint: [16 row bytes]} for an 8x16 C-spacing BDF."""
    glyphs = {}
    ascent = 12  # FONTBOUNDINGBOX 8 16 0 -4
    with open(path) as f:
        lines = iter(f)
        for line in lines:
            if line.startswith("FONT_ASCENT"):
                ascent = int(line.split()[1])
            if not line.startswith("STARTCHAR"):
                continue
            enc = None
            bbx = (8, 16, 0, -4)
            rows = None
            for line in lines:
                if line.startswith("ENCODING"):
                    enc = int(line.split()[1])
                    if enc not in wanted:
                        break
                elif line.startswith("BBX"):
                    p = line.split()
                    bbx = (int(p[1]), int(p[2]), int(p[3]), int(p[4]))
                elif line.startswith("BITMAP"):
                    rows = []
                    for line in lines:
                        if line.startswith("ENDCHAR"):
                            break
                        rows.append(int(line.strip(), 16))
                    break
            if enc is None or rows is None:
                continue
            # Place the BBX-sized bitmap into the 8x16 cell.
            w, h, xoff, yoff = bbx
            cell = [0] * 16
            top = ascent - (yoff + h)
            for r, bits in enumerate(rows):
                y = top + r
                if 0 <= y < 16:
                    # BDF rows are left-aligned in ceil(w/8) bytes
                    cell[y] = (bits >> xoff) & 0xFF if xoff >= 0 else (bits << -xoff) & 0xFF
            glyphs[enc] = cell
    return glyphs


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    bdf_path = sys.argv[1]

    base = {}
    exec(open(os.path.join(ROOT, "lib", "vga2_8x16.py")).read(), base)
    font = bytearray(base["_FONT"])
    assert len(font) == 4096, len(font)

    glyphs = parse_bdf(bdf_path, set(SLOTS.values()))
    missing = [hex(cp) for cp in SLOTS.values() if cp not in glyphs]
    if missing:
        sys.exit("BDF is missing glyphs: %s" % missing)

    for slot, cp in SLOTS.items():
        font[slot * 16:(slot + 1) * 16] = bytes(glyphs[cp])

    out = os.path.join(ROOT, "lib", "vga2_8x16_cp866.py")
    with open(out, "w") as f:
        f.write('"""vga2_8x16 with CP866-layout Cyrillic (+ Bulgarian '
                'Ѝ/ѝ at 0xFC/0xFD).\n\nGenerated by tools/gen_cp866_font.py '
                '— CP437 base glyphs from vga2_8x16.py,\nCyrillic from '
                'UNI-VGA (u_vga16.bdf, D. Bolkhovityanov, X license).\n'
                'Do not edit by hand. The ui.py _CYR table must match this '
                'layout.\n"""\n')
        f.write("WIDTH = 8\nHEIGHT = 16\nFIRST = 0x00\nLAST = 0xff\n_FONT =\\\n")
        for i in range(0, 4096, 16):
            f.write("b'" + "".join("\\x%02x" % b for b in font[i:i + 16]) + "'\\\n")
        f.write("\nFONT = memoryview(_FONT)\n")
    print("wrote %s (%d bytes bitmap, %d slots replaced)"
          % (out, len(font), len(SLOTS)))


if __name__ == "__main__":
    main()
