# MicroPython frozen manifest for T-Deck
# This freezes app .py files into firmware ROM.
#
# Benefits:
#   - Zero filesystem RAM usage (executed from ROM)
#   - Instant import (no filesystem read + parse)
#   - Replaces all .mpy bytecode files
#
# Everything the app imports has to be listed here or be a built-in C module
# (tools/c_modules/) — the VFS image tools/build_vfs.py ships carries only
# main.py, tdeck_config.py and logo.jpg, so an unfrozen import is a device
# that boots and then fails at first use. The codec/crypto modules that used
# to be natmod .mpy files on the filesystem (ed25519_fast, bz2_fast,
# codec2_fast, tjpgd_fast, webp_fast) are built-in C modules now.

# Include the default ESP32-S3 manifest first
include("$(PORT_DIR)/boards/manifest.py")

# Project root — the manifest path is this file's own location.
# makemanifest.py resolves the path before exec, so we can extract it
# from the -v args. Use TDECK_ROOT env var set by build_firmware.sh.
import os
_root = os.environ["TDECK_ROOT"]
# The Reticulum stack + board presets come from the uP-reticulum submodule
# (vendor/uP-reticulum) — run `git submodule update --init` before building.
_vendor = _root + "/vendor/uP-reticulum/firmware"

# --- App modules (top-level) ---
# tdeck_config.py  — on filesystem, user-editable
# tdeck_node.py    — on filesystem as main.py, user-editable
freeze(_root, "ui.py")
freeze(_root, "sound.py")
freeze(_root, "es7210.py")
freeze(_root, "micron.py")
freeze(_root, "nomad_browser.py")
freeze(_root, "rnsh_proto.py")
freeze(_root, "rnsh_client.py")
freeze(_root, "terminal.py")
freeze(_vendor, "lora_boards.py")
freeze(_vendor + "/peripherals", "adc_reader.py")

# --- Fonts ---
# System font (tdeck_node imports this as `font`): Spleen 8x16, BSD-2, in the
# CP437+CP866 slot layout — generated by tools/gen_shell_font.py.
freeze(_root + "/lib", "spleen_8x16.py")
# The original VGA ROM font stays frozen: it is the one-line revert for the
# system font, and gen_shell_font.py's --fallback source for the CP866 slots
# Spleen lacks. Drop it if you're sure you won't go back.
freeze(_root + "/lib", "vga2_8x16_cp866.py")
# Shell terminal fonts (same slot layout, smaller cells). Drop the rungs you
# don't use from both this list and ui._SHELL_FONTS.
#   spleen_6x12 -> 53x16   shell_6x10 -> 53x19
#   shell_5x8   -> 64x24   shell_4x6  -> 80x32
# lib/shell_6x12.py is NOT frozen — it is only the --fallback source used when
# regenerating spleen_6x12.
freeze(_root + "/lib", "spleen_6x12.py")
freeze(_root + "/lib", "shell_6x10.py")
freeze(_root + "/lib", "shell_5x8.py")
freeze(_root + "/lib", "shell_4x6.py")

# --- SX1262 radio driver ---
# micropython-lib's lora / lora-sx126x / lora-sync, vendored verbatim in
# lib/lora (see lib/lora/UPSTREAM.md for versions and provenance). This is
# what urns/interfaces/lora.py imports as `from lora import SX1262`; without
# it the radio never comes up. Pure bytecode, so it freezes like the rest —
# it only ever lived on the filesystem because it arrived via `mip install`.
freeze(_root + "/lib", "lora/__init__.py")
freeze(_root + "/lib", "lora/modem.py")
freeze(_root + "/lib", "lora/sx126x.py")
freeze(_root + "/lib", "lora/sync_modem.py")

# --- urns (Reticulum stack) ---
freeze(_vendor, "urns/__init__.py")
freeze(_vendor, "urns/bz2dec.py")
freeze(_vendor, "urns/buffer.py")
freeze(_vendor, "urns/channel.py")
freeze(_vendor, "urns/const.py")
freeze(_vendor, "urns/destination.py")
freeze(_vendor, "urns/identity.py")
freeze(_vendor, "urns/link.py")
freeze(_vendor, "urns/log.py")
freeze(_vendor, "urns/lxmf.py")
freeze(_vendor, "urns/packet.py")
freeze(_vendor, "urns/resource.py")
freeze(_vendor, "urns/reticulum.py")
freeze(_vendor, "urns/transport.py")
freeze(_vendor, "urns/umsgpack.py")

# --- urns/crypto ---
freeze(_vendor, "urns/crypto/__init__.py")
freeze(_vendor, "urns/crypto/aes.py")
freeze(_vendor, "urns/crypto/ed25519.py")
freeze(_vendor, "urns/crypto/hashes.py")
freeze(_vendor, "urns/crypto/hkdf.py")
freeze(_vendor, "urns/crypto/hmac.py")
freeze(_vendor, "urns/crypto/pkcs7.py")
freeze(_vendor, "urns/crypto/sha512.py")
freeze(_vendor, "urns/crypto/token.py")
freeze(_vendor, "urns/crypto/x25519.py")

# --- urns/crypto/pure25519 ---
freeze(_vendor, "urns/crypto/pure25519/__init__.py")
freeze(_vendor, "urns/crypto/pure25519/_ed25519.py")
freeze(_vendor, "urns/crypto/pure25519/basic.py")
freeze(_vendor, "urns/crypto/pure25519/ed25519_oop.py")
freeze(_vendor, "urns/crypto/pure25519/eddsa.py")

# --- urns/interfaces ---
freeze(_vendor, "urns/interfaces/__init__.py")
freeze(_vendor, "urns/interfaces/e32.py")
freeze(_vendor, "urns/interfaces/lora.py")
freeze(_vendor, "urns/interfaces/serial.py")
freeze(_vendor, "urns/interfaces/tcp.py")
freeze(_vendor, "urns/interfaces/udp.py")
