# MicroPython frozen manifest for T-Deck
# This freezes app .py files into firmware ROM.
#
# Benefits:
#   - Zero filesystem RAM usage (executed from ROM)
#   - Instant import (no filesystem read + parse)
#   - Replaces all .mpy bytecode files (but NOT natmod .mpy files)
#
# Natmod .mpy files (ed25519_fast, bz2_fast, codec2_fast, tjpgd_fast, webp_fast)
# must STAY on the filesystem — they contain native machine code that can't be frozen.

# Include the default ESP32-S3 manifest first
include("$(PORT_DIR)/boards/manifest.py")

# Project root — the manifest path is this file's own location.
# makemanifest.py resolves the path before exec, so we can extract it
# from the -v args. Use TDECK_ROOT env var set by build_firmware.sh.
import os
_root = os.environ["TDECK_ROOT"]
# The Reticulum stack + board presets come from the uP-reticulum submodule
# (vendor/uP-reticulum) — run `git submodule update --init` before building.
_vendor = _root + "/vendor/uP-reticulum/firmware"

# --- App modules (top-level) ---
# tdeck_config.py  — on filesystem, user-editable
# tdeck_node.py    — on filesystem as main.py, user-editable
freeze(_root, "ui.py")
freeze(_root, "sound.py")
freeze(_root, "es7210.py")
freeze(_root, "micron.py")
freeze(_root, "nomad_browser.py")
freeze(_root, "rnsh_proto.py")
freeze(_root, "rnsh_client.py")
freeze(_root, "terminal.py")
freeze(_vendor, "lora_boards.py")
freeze(_vendor + "/peripherals", "adc_reader.py")

# --- Font ---
# CP437 base + CP866-slot Cyrillic; generated by tools/gen_cp866_font.py
freeze(_root + "/lib", "vga2_8x16_cp866.py")

# --- urns (Reticulum stack) ---
freeze(_vendor, "urns/__init__.py")
freeze(_vendor, "urns/bz2dec.py")
freeze(_vendor, "urns/buffer.py")
freeze(_vendor, "urns/channel.py")
freeze(_vendor, "urns/const.py")
freeze(_vendor, "urns/destination.py")
freeze(_vendor, "urns/identity.py")
freeze(_vendor, "urns/link.py")
freeze(_vendor, "urns/log.py")
freeze(_vendor, "urns/lxmf.py")
freeze(_vendor, "urns/packet.py")
freeze(_vendor, "urns/resource.py")
freeze(_vendor, "urns/reticulum.py")
freeze(_vendor, "urns/transport.py")
freeze(_vendor, "urns/umsgpack.py")

# --- urns/crypto ---
freeze(_vendor, "urns/crypto/__init__.py")
freeze(_vendor, "urns/crypto/aes.py")
freeze(_vendor, "urns/crypto/ed25519.py")
freeze(_vendor, "urns/crypto/hashes.py")
freeze(_vendor, "urns/crypto/hkdf.py")
freeze(_vendor, "urns/crypto/hmac.py")
freeze(_vendor, "urns/crypto/pkcs7.py")
freeze(_vendor, "urns/crypto/sha512.py")
freeze(_vendor, "urns/crypto/token.py")
freeze(_vendor, "urns/crypto/x25519.py")

# --- urns/crypto/pure25519 ---
freeze(_vendor, "urns/crypto/pure25519/__init__.py")
freeze(_vendor, "urns/crypto/pure25519/_ed25519.py")
freeze(_vendor, "urns/crypto/pure25519/basic.py")
freeze(_vendor, "urns/crypto/pure25519/ed25519_oop.py")
freeze(_vendor, "urns/crypto/pure25519/eddsa.py")

# --- urns/interfaces ---
freeze(_vendor, "urns/interfaces/__init__.py")
freeze(_vendor, "urns/interfaces/e32.py")
freeze(_vendor, "urns/interfaces/lora.py")
freeze(_vendor, "urns/interfaces/serial.py")
freeze(_vendor, "urns/interfaces/tcp.py")
freeze(_vendor, "urns/interfaces/udp.py")
